#!/usr/bin/env bash
set -e

LAZYGIT_VERSION=0.43.1
DELTA_VERSION=0.18.0
NODE_VERSION=21

CURRENT_DIR=$(
  cd "$(dirname "$0")"
  pwd
)

if [ ! -d "$HOME"/.config ]; then
  mkdir "${HOME}"/.config
fi

ln -vfsn "${CURRENT_DIR}" "${HOME}"/.config/nvim

# mise install
if command -v mise >/dev/null 2>&1; then
  echo "mise is installed."
else
  echo "mise is not installed.\nstart installing..."

  curl https://mise.run | sh
  ln -vfsn $HOME/.local/bin/mise /usr/local/bin/mise

  echo 'eval "$(~/.local/bin/mise activate bash)"' >>~/.bashrc
  # for fish
  if command -v fish >/dev/null 2>&1; then
    mkdir -p "$HOME"/.config/fish
    echo '~/.local/bin/mise activate fish | source' >>~/.config/fish/config.fish
  fi
fi

if [ ! -d "$HOME"/.config/mise/conf.d ]; then
  mkdir -p $HOME/.config/mise/conf.d
fi

ln -vfsn ${CURRENT_DIR}/mise.nvim.toml $HOME/.config/mise/conf.d/mise.nvim.toml

# install tools by mise
mise i
